# Generated by Django 3.2.9 on 2022-07-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='users',
        ),
    ]
