# Generated by Django 3.2.9 on 2022-08-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_cart_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_no', models.CharField(max_length=2000)),
                ('boat_name', models.CharField(max_length=2000)),
                ('no_of_fishermen', models.IntegerField()),
                ('boat_length', models.CharField(max_length=2000)),
                ('upload_photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
